clear
[sig2,fe1]=audioread("Motis_musique_cut.mp3");
sig1=sig2(:,1)';
chroma=make_chromagramme(sig1,fe1,1000);
Auto=make_auto(chroma);
mfcc=make_mfcc_gramme(sig1,fe1,40);
Auto2=make_auto(mfcc);
figure()
image(Auto,'CDataMapping','scaled');
colorbar
colormap("turbo")
figure()
image(Auto2,'CDataMapping','scaled');
colorbar
colormap("turbo")
figure()
image(mfcc,'CDataMapping','scaled');
colorbar
colormap("turbo")
figure()
image(chroma,'CDataMapping','scaled');
colorbar
colormap("turbo")
yticks([1 2 3 4 5 6 7 8 9 10 11 12])
yticklabels({'la','la#','si','do','do#','ré','ré#','mi','fa','fa#','sol','sol#'})
